apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: twfqcg2si-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: twfqcg2si-nodejs 
  name: twfqcg2si-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: twfqcg2si-nodejs 
