apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: twfqcg2si-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:19378de2df9d082e509a330f56b298cf6dd9c0da@sha256:9c31f6fb80f378a148419722e0ad0654ddc0e039683ccfdf41ec82e40c6f5078
          name: container-image
